### PR TITLE
Add -language:strictEquality compiler flag

### PR DESCRIPTION
**Pull request by joan38**

### CODE REVIEW

**Comment by joan38** [comment]
cc @satorg

**Review by satorg — APPROVED** [review]
Thank you!

**Comment by satorg** [comment]
Actually, it took me some time to check this PR.
Turns out that in Scala3 the `-language` option works in a bit weird way:
- `-language:help` does not provide a list of available choices.
- `-lanugage:ANY_INCORRECT_OPTION` does not fail with an error.

All the Scala2 versions I checked with work in a more expected way....

I created a topic about it in [Scala Contributors](https://contributors.scala-lang.org/t/scala3-language-compiler-option-issues/6617) hoping to get some clarification on that.

**Comment by joan38** [comment]
I see.
So are we not adding this to the lib until we know it's failing if this option gets removed in the future?

**Comment by satorg** [comment]
No, why – I just allowed some time for dust to settle around this option (and the associated bug in the compiler). But then I blissfully forgot about this PR, sorry about it 😊 

Thank you for the PR!

**Comment by joan38** [comment]
Thanks @satorg
Are we releasing a new version soon? I feel we had a lot of changes in since last year.

**Comment by satorg** [comment]
> Are we releasing a new version soon? I feel we had a lot of changes in since last year.

@DavidGregory084 , @armanbilge , are we?
I personally don't mind, not sure if I can though.

<sub>To be honest, I've never _ever_ cut off any release on GitHub myself 😨  . David, Arman, how do we do it, just in case?</sub>

**Comment by TonioGela** [comment]
> > Are we releasing a new version soon? I feel we had a lot of changes in since last year.
> 
> @DavidGregory084 , @armanbilge , are we? I personally don't mind, not sure if I can though.
> 
> To be honest, I've never _ever_ cut off any release on GitHub myself 😨 . David, Arman, how do we do it, just in case?

I can publish it, if we all agree that it's time to. Consider that in order to get in sbt-tpolecat we would also need to release that.

**Comment by joan38** [comment]
I personally use this lib directly in Mill and stopped using mill-tpolcat:
https://github.com/joan38/kubernetes-client/blob/main/build.sc#L27

So I'm ok for sbt or mill-tpolcat to not pick up this version.

**Comment by armanbilge** [comment]
> To be honest, I've never _ever_ cut off any release on GitHub myself 😨 . David, Arman, how do we do it, just in case?

https://typelevel.org/sbt-typelevel/faq.html#how-do-i-cut-a-release

**Comment by joan38** [comment]
@TonioGela any news on the release? Thanks

**Comment by joan38** [comment]
@satorg @armanbilge Any way we could cut a release?

**Comment by satorg** [comment]
@joan38, I think I can try to arrange it on the weekends (if there are no objections, of course).
Thank you for your contribution!

**Comment by TonioGela** [comment]
> @TonioGela any news on the release? Thanks

Sorry for the delay, I've completely skipped this notification.
0.1.5 was just released, enjoy.

**Pull request merged**
